help formatting + exit

diff --git a/dl_mod b/dl_mod
--- a/dl_mod
+++ b/dl_mod
@@ -5,8 +5,12 @@
 Help()
 {
     #Display help
-    echo "-m MOD_ID (Required)"
-    echo "-l Location of server directory (Required)"
+    echo 
+    echo "   Options:"
+    echo "      -m MOD_ID (Required)"
+    echo "      -l Location of server directory (Required)"
+    echo
+    exit 1
 
 }
 
